"""
prompts 包公开 API。
"""

from prompts.evaluator_prompt import EVALUATOR_SYSTEM_PROMPT
from prompts.interviewer_prompt import (
    INTERVIEWER_FOLLOW_UP_TEMPLATE,
    INTERVIEWER_NEW_QUESTION_TEMPLATE,
    INTERVIEWER_SYSTEM_PROMPT,
)
from prompts.planner_prompt import PLANNER_SYSTEM_PROMPT, PLANNER_USER_TEMPLATE
from prompts.reporter_prompt import REPORTER_SYSTEM_PROMPT, REPORTER_USER_TEMPLATE

__all__ = [
    "PLANNER_SYSTEM_PROMPT",
    "PLANNER_USER_TEMPLATE",
    "INTERVIEWER_SYSTEM_PROMPT",
    "INTERVIEWER_NEW_QUESTION_TEMPLATE",
    "INTERVIEWER_FOLLOW_UP_TEMPLATE",
    "EVALUATOR_SYSTEM_PROMPT",
    "REPORTER_SYSTEM_PROMPT",
    "REPORTER_USER_TEMPLATE",
]
